version: '3.7'
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    depends_on:
    - web_service
    - grpc
    networks:
    - envoymesh
    ports:
    - "8000:8000"
    volumes:
    - ./envoy.yaml:/etc/envoy.yaml
    - "./build:/run/build"

  web_service:
    build:
      context: .
      dockerfile: Dockerfile-web-service
    networks:
    - envoymesh

  grpc:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    environment:
      PYTHONPATH: "/app/build"
    command:
    - python3
    - /app/src/transform_grpc_server.py
    volumes:
    - .:/app/
    networks:
    - envoymesh

  # Command for generating Python modules of our gPRC protobuf file
  make-py-grpc:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    command:
    - python3
    - -m
    - grpc_tools.protoc
    - -I/run/src/protobuf
    - --python_out=/run/build
    - --grpc_python_out=/run/build
    - '/run/src/protobuf/transform.proto'
    volumes:
    - ./src:/run/src
    - ./build:/run/build
    profiles:
    - "cmd"

  # Command for generating cpp files of our gPRC protobuf file
  make-cpp-grpc:
    build:
      context: .
      dockerfile: Dockerfile-protoc
    command:
    - protoc
    - --proto_path=/run/src/protobuf
    - --cpp_out=/run/build
    - '/run/src/protobuf/transform.proto'
    volumes:
    - ./src:/run/src
    - ./build:/run/build
    profiles:
    - "cmd"

networks:
  envoymesh: {}
