version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: true
    resource_class: xlarge

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: generate grpc files
          command: |
            docker-compose run make-py-grpc
            docker-compose run make-cpp-grpc

      - run:
          name: build wasm sdk
          command: |
            cd /tmp
            git clone https://github.com/proxy-wasm/proxy-wasm-cpp-sdk.git
            cd proxy-wasm-cpp-sdk
            # Turns out the very next commit brings in changes that would break
            # the build, probably due to different version of toolchain.
            # so we pin the commit to ensure it's working
            git checkout c17bf8257e5ebad2399f95cc15c8ff64e515519f
            docker build -t wasmsdk:v2 -f Dockerfile-sdk .

      - run:
          name: build wasm filter
          command: |
            docker run -v $PWD:/work -w /work  wasmsdk:v2 /build_wasm.sh

      - store_artifacts:
          path: build/transform.wasm

workflows:
  build:
    jobs:
      - build
